---
- name: Install BIMData.io stack
  hosts: all
  gather_facts: false
  become: true
  any_errors_fatal: true
  roles:
    - role: prepare_vars
      tags: ["always"]
    - role: docker
      tags: ["docker"]
      when:
        - install_docker | bool
        - not install_offline | bool
    - role: prerequisites
      tags: ["prerequisites"]

# DBs
    - role: pg_upgrade
      tags: ["database", "db"]
      when:
        - inventory_hostname in groups["db"]
        - not use_external_db | bool
    - role: bimdata_db
      tags: ["database", "db"]
      when:
        - inventory_hostname in groups["db"]
        - not use_external_db | bool
        - inventory_hostname not in groups["app"]

# RabbitMQ
    - role: rabbitmq_upgrade
      tags: ["rabbitmq", "app"]
      when:
        - not _first_deploy
        - inventory_hostname in groups["app"]
        - not use_external_rabbitmq | bool

# Apps
    - role: bimdata
      tags: ["bimdata", "app"]
      when:
        - inventory_hostname in groups["app"]

# Workers
    - role: bimdata_workers
      tags: ["bimdata", "worker"]
      when:
        - inventory_hostname in groups["workers"]
        - inventory_hostname not in groups["app"]

# Post-run
    - role: post_run
      tags: ["post_run"]
