---
- name: "Create docker-compose file."
  template:
    src: compose-migration-apps.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    mode: 0640
  vars:
    docker_api_tag: apps_from_connect_to_api

- name: "Create dump folder."
  file:
    path: "{{ bimdata_path }}/dump"
    state: directory
    mode: 0750

- name: "Copy database dumps."
  copy:
    src: "old_env/dump/{{ item }}.sql"
    dest: "{{ bimdata_path }}/dump/{{ item }}.sql"
    mode: 0640
  loop: "{{ db_list }}"

- name: "Pull needed images."
  command: docker-compose -f {{ bimdata_path }}/docker-compose.yml pull

- name: "Start containers"
  command: "docker-compose -f {{ bimdata_path }}/docker-compose.yml up --remove-orphans --detach"

- name: "Restore the dump."
  shell: "cat {{ bimdata_path }}/dump/{{ item }}.sql | /usr/bin/docker exec -i {{ item }}-db psql -U {{ lookup('vars', 'db_'+item+'_user') }} -d {{ item }} 1>/dev/null"
  loop: "{{ db_list }}"

- name: "Copy scripts"
  copy:
    src: "migrations/apps_from_connect_to_api/{{ item }}"
    dest: "{{ bimdata_path }}/{{ item }}"
    mode: 0640
  loop:
    - restore_apps.py
    - create_apps_in_django.py

- name: Install script migration requirements
  pip:
    name: docker==5.0.3

- name: "Launch apps migration"
  command: "python3 {{ bimdata_path }}/restore_apps.py"
  register: migration

- name: "Fix migration dependancies"
  command: "docker exec {{ db_api_name }}-db psql -U {{ db_api_user }} -d {{ db_api_name }} -c \"UPDATE django_migrations SET name = '0065_ifc_gltf_with_openings_file' WHERE name = '0064_ifc_gltf_with_openings_file'\""

- name: "Stop containers"
  command: "docker-compose -f {{ bimdata_path }}/docker-compose.yml stop"

- name: "Remove containers"
  command: "docker-compose -f {{ bimdata_path }}/docker-compose.yml rm"

- name: remove docker-compose migration file
  file:
    state: absent
    path: "{{ bimdata_path }}/docker-compose.yml"

- name: Add migration name
  lineinfile:
    path: "{{ bimdata_path }}/.migrations"
    regexp: "^apps_from_connect_to_api:"
    line: "apps_from_connect_to_api: ok"
    create: true
    mode: 0640
