---
# Restart doesn't respect depends_on and other stuff, so down + up instead
# Cant' use block in handlers, so include_tasks instead
- name: Restart all services
  ansible.builtin.include_tasks: restart.yml
  when: not _first_deploy | bool

- name: Restart nginx
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: nginx-proxy
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart iam
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: iam
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart connect
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: connect
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart platform-back
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: platform-back
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart platform-back-cron
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: platform-back-cron
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart marketplace-back
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: marketplace-back
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool

- name: Restart sso-invitation
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    services: sso-invitation
    state: restarted
  when:
    - not _first_deploy | bool
    - _app_all_restart is not defined or not _app_all_restart | bool
