---
- name: Include tasks for prerequisites installation
  ansible.builtin.include_tasks: "{{ install_offline | bool | ternary('offline.yml', 'online.yml') }}"

- name: Configure local /etc/hosts if needed
  delegate_to: localhost
  connection: local
  delegate_facts: true
  run_once: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |-
      {% for item in docker_extra_hosts %}
      {{ item | split(':') | last }} {{ item | split(':') | first }}
      {% endfor %}
    marker: "# Ansible managed {mark}"
    unsafe_writes: true
    state: present
  when:
    - ansible_use_extra_hosts is defined
    - ansible_use_extra_hosts | bool

- name: "Check if legacy virtualenv exists"
  ansible.builtin.stat:
    path: "{{ bimdata_path }}/venv"
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: stat_venv

- name: "Define fact for legacy virtualenv"
  ansible.builtin.set_fact:
    _legacy_venv_cleanup: "{{ stat_venv.stat.isdir is defined and stat_venv.stat.isdir }}"

- name: "Cleanup old docker compose if needed"
  when: _legacy_venv_cleanup
  block:
    - name: "Stop all containers setup with compose < 2"
      community.docker.docker_compose:
        project_src: "{{ bimdata_path }}"
        remove_orphans: true
        state: absent
      vars:
        ansible_python_interpreter: "{{ bimdata_path }}/venv/bin/python"
# Enf of block
