---
- name: Include tasks for prerequisites installation
  ansible.builtin.include_tasks: "{{ install_offline | bool | ternary('offline.yml', 'online.yml') }}"

- name: Configure local /etc/hosts if needed
  delegate_to: localhost
  connection: local
  delegate_facts: true
  run_once: true
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |-
      {% for item in docker_extra_hosts %}
      {{ item | split(':') | last }} {{ item | split(':') | first }}
      {% endfor %}
    marker: "# Ansible managed {mark}"
    unsafe_writes: true
    state: present
  when:
    - ansible_use_extra_hosts is defined
    - ansible_use_extra_hosts | bool
