---
# Can't use unarchived, this will extract the tar, we only want to remove the bzip2 compression
- name: Copy offline docker requirements
  ansible.builtin.copy:
    src: "offline/docker/{{ item.src }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum | default(omit) }}"
    mode: "0640"
  loop: "{{ install_offline_docker }}"
  when: item.group is not defined or inventory_hostname in groups[item.group]

# Not indempodent at all
- name: Extract docker requirements
  ansible.builtin.command: "bzip2 -k -d -f {{ item.dest }}/{{ item.src }}"
  loop: "{{ install_offline_docker }}"
  when: item.group is not defined or inventory_hostname in groups[item.group]
  changed_when: true

# Docker_image do not allow multiple load at the same time, this is easier but not indempodent
- name: Import docker images
  ansible.builtin.command: "docker load -i {{ item.dest }}/{{ item.src | splitext | first }}"
  loop: "{{ install_offline_docker }}"
  when: item.group is not defined or inventory_hostname in groups[item.group]
  changed_when: true
