---
- name: Login to the define docker registries
  community.docker.docker_login:
    registry: "{{ item.url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_registries }}"
  environment: "{{ proxy_env }}"
  no_log: true
  when:
    - docker_registries is defined
