---
- name: "Create needed directories."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ bimdata_path }}/scripts"
    - "{{ bimdata_dockerfiles_path }}"
    - "{{ bimdata_docker_volume_path }}/keycloak"
    - "{{ bimdata_docker_volume_path }}/web/static/api"
    - "{{ bimdata_docker_volume_path }}/web/static/api_storage"
    - "{{ bimdata_docker_volume_path }}/web/static/connect"
    - "{{ bimdata_docker_volume_path }}/web/static/platform_back"
    - "{{ bimdata_docker_volume_path }}/web/conf.d"
    - "{{ bimdata_docker_volume_path }}/web/vhost.d"
    - "{{ bimdata_docker_volume_path }}/web/certs"

- name: "Create needed directories for db if needed."
  file:
    path: "{{ bimdata_docker_volume_path }}/db/{{ item }}"
    state: directory
    owner: 70
    group: 70
    mode: 0750
  loop:
    - api
    - connect
    - platform
    - iam
  when:
    - not use_external_db
    - db_on_app

- name: "Include tasks for TLS."
  include_tasks: tls.yml

- name: "Copy .dockerignore file."
  copy:
    src: dockerignore
    dest: "{{ bimdata_docker_volume_path }}/.dockerignore"
    mode: 0640

- name: "Copy platform dockerfiles."
  copy:
    src: "dockerfiles/platform.dockerfile"
    dest: "{{ bimdata_dockerfiles_path }}/"
    mode: 0640

- name: "Copy preview dockerfiles if needed."
  copy:
    src: "dockerfiles/preview.dockerfile"
    dest: "{{ bimdata_dockerfiles_path }}/"
    mode: 0640

- name: "Copy nginx custom configuration."
  template:
    src: web/custom.conf.j2
    dest: "{{ bimdata_docker_volume_path }}/web/conf.d/custom.conf"
    mode: 0640

- name: "Copy vhost override configuration."
  template:
    src: web/vhost.conf.j2
    dest: "{{ bimdata_docker_volume_path }}/web/vhost.d/{{ item.vhost }}"
    mode: 0640
  loop: "{{ nginx_vhost_override }}"

- name: "Copy keycloak realm."
  copy:
    src: "keycloak/bimdata-realm.json"
    dest: "{{ bimdata_docker_volume_path }}/keycloak/"
    mode: 0640

- name: "Create docker-compose file."
  template:
    src: compose-app.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    mode: 0640

- name: "Pull needed images."
  command: docker-compose -f {{ bimdata_path }}/docker-compose.yml pull

- name: "Build needed images."
  command: docker-compose -f {{ bimdata_path }}/docker-compose.yml build --pull

- name: "Start containers"
  command: "docker-compose -f {{ bimdata_path }}/docker-compose.yml up --detach"

- name: "Include tasks for initialization."
  include_tasks: first-init.yml
