---
- name: "Create needed directories."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ bimdata_path }}/scripts"
    - "{{ bimdata_docker_volume_path }}/keycloak"
    - "{{ bimdata_docker_volume_path }}/web/conf.d"
    - "{{ bimdata_docker_volume_path }}/web/vhost.d"
    - "{{ bimdata_docker_volume_path }}/web/certs"

- name: "Create needed directories for local storage."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ bimdata_docker_volume_path }}/web/api_storage"
    - "{{ bimdata_docker_volume_path }}/web/connect_storage"
  when: not swift_enabled | bool

- name: "Create needed directories for db if needed."
  file:
    path: "{{ bimdata_docker_volume_path }}/db/{{ item }}"
    state: directory
    owner: 70
    group: 70
    mode: 0700
  loop:
    - api
    - connect
    - platform
    - iam
    - marketplace
  when:
    - not use_external_db
    - db_on_app

- name: "Copy pre-generated DH params."
  copy:
    src: pregen-dhparams.pem
    dest: "{{ bimdata_docker_volume_path }}/web/dhparam.pem"
    mode: 0640
  when: nginx_use_pregen_dh
  notify: "Restart nginx."

- name: "Generate custom DH params."
  openssl_dhparam:
    path: "{{ bimdata_docker_volume_path }}/web/dhparam.pem"
    size: "{{ nginx_dhparam_size | default(omit) }}"
  when: not nginx_use_pregen_dh | bool
  notify: "Restart nginx."

- name: "Include tasks for TLS."
  include_tasks: tls.yml

- name: "Copy nginx custom configuration."
  template:
    src: web/custom.conf.j2
    dest: "{{ bimdata_docker_volume_path }}/web/conf.d/custom.conf"
    mode: 0640
  notify: "Restart nginx."

- name: "Copy vhost override configuration."
  template:
    src: web/vhost.conf.j2
    dest: "{{ bimdata_docker_volume_path }}/web/vhost.d/{{ item.vhost }}"
    mode: 0640
  loop: "{{ nginx_vhost_override }}"
  notify: "Restart nginx."

- name: "Copy keycloak realm."
  template:
    src: "keycloak/bimdata-realm.json.j2"
    dest: "{{ bimdata_docker_volume_path }}/keycloak/bimdata-realm.json"
    mode: 0640
  notify: "Restart iam."

- name: "Create docker-compose file."
  template:
    src: compose-app.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    mode: 0640

- name: "Start the containers."
  docker_compose:
    project_src: "{{ bimdata_path }}"
    pull: true
    remove_orphans: true
    state: present
  vars:
    ansible_python_interpreter: "{{ bimdata_venv_path }}/bin/python"

# - name: "Include tasks for initialization."
#   include_tasks: first-init.yml
