---
- name: Stop and start all bimdata services
  block:
    - name: Stop all bimdata services
      community.docker.docker_compose_v2:
        project_src: "{{ bimdata_path }}"
        state: stopped
    - name: Start all bimdata services
      community.docker.docker_compose_v2:
        project_src: "{{ bimdata_path }}"
    - name: Set fact that all container where restart
      ansible.builtin.set_fact:
        _app_all_restart: true
