---
- when: tls_enabled | bool
  block:
  - name: "Copy the TLS CA."
    template:
      src: templates/tls/ca.crt.j2
      dest: "{{ bimdata_docker_volume_path }}/ca.crt"
      owner: root
      group: root
      mode: 0644
    notify: "Restart all services."

  - name: "Copy the app TLS key."
    template:
      src: templates/tls/key.j2
      dest: "{{ bimdata_docker_volume_path }}/web/certs/{{ lookup('vars', item + '_dns_name') }}.key"
      owner: root
      group: root
      mode: 0640
    loop: "{{ needed_cert_tls }}"
    notify: "Restart nginx."

  - name: "Copy the app TLS cert."
    template:
      src: templates/tls/cert.j2
      dest: "{{ bimdata_docker_volume_path }}/web/certs/{{ lookup('vars', item + '_dns_name') }}.crt"
      owner: root
      group: root
      mode: 0640
    loop: "{{ needed_cert_tls }}"
    notify: "Restart nginx."

- when: not tls_enabled | bool
  block:
  - name: "Delete the app TLS key."
    file:
      path: "{{ bimdata_docker_volume_path }}/web/certs/{{ lookup('vars', item + '_dns_name') }}.key"
      state: absent
    loop: "{{ needed_cert_tls }}"
    notify: "Restart nginx."

  - name: "Delete the app TLS cert."
    file:
      path: "{{ bimdata_docker_volume_path }}/web/certs/{{ lookup('vars', item + '_dns_name') }}.crt"
      state: absent
    loop: "{{ needed_cert_tls }}"
    notify: "Restart nginx."
