---
- name: "Create needed directories."
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  loop:
    - "{{ bimdata_path }}"
    - "{{ bimdata_dockerfiles_path }}"
    - "{{ bimdata_docker_volume_path }}/web/certs"

- name: "Copy the TLS CA."
  template:
    src: templates/tls/ca.crt.j2
    dest: "{{ bimdata_docker_volume_path }}/web/certs/ca.crt"
    owner: root
    group: root
    mode: 0644

- name: "Copy .dockerignore file."
  copy:
    src: dockerignore
    dest: "{{ bimdata_docker_volume_path }}/.dockerignore"
    mode: 0640

- name: "Copy dockerfiles."
  copy:
    src: "dockerfiles/{{ item }}"
    dest: "{{ bimdata_dockerfiles_path }}/{{ item }}"
    mode: 0640
  loop:
    - bases.dockerfile
    - preview.dockerfile

- name: "Create docker-compose file."
  template:
    src: compose-workers.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0640

- name: "Pull needed images."
  command: docker-compose -f {{ bimdata_path }}/docker-compose.yml pull

- name: "Build needed images."
  command: docker-compose -f {{ bimdata_path }}/docker-compose.yml build --pull

- name: "Start containers"
  command: "docker-compose -f {{ bimdata_path }}/docker-compose.yml up --detach"
