---
- name: "Create needed directories."
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ bimdata_path }}"
    - "{{ bimdata_dockerfiles_path }}"
    - "{{ bimdata_docker_volume_path }}/web/certs"

- name: "Copy the TLS CA."
  template:
    src: templates/tls/ca.crt.j2
    dest: "{{ bimdata_docker_volume_path }}/ca.crt"
    owner: root
    group: root
    mode: 0644
  when: tls_enabled | bool
  notify: "Restart all services."

- name: "Create docker-compose file."
  template:
    src: compose-workers.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0640

- name: "Start the containers."
  docker_compose:
    project_src: "{{ bimdata_path }}"
    pull: true
    remove_orphans: true
    state: present
  vars:
    ansible_python_interpreter: "{{ bimdata_venv }}/bin/python"
