---
- name: Create needed directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ bimdata_path }}"
    - "{{ bimdata_docker_volume_path }}/web/certs"

- name: Copy the TLS CA
  ansible.builtin.template:
    src: templates/tls/ca.crt.j2
    dest: "{{ bimdata_docker_volume_path }}/ca.crt"
    owner: root
    group: root
    mode: "0644"
  when: tls_custom_ca | bool
  notify: Restart all services

- name: Create docker-compose file
  ansible.builtin.template:
    src: compose-workers.yml.j2
    dest: "{{ bimdata_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0640"

- name: Start the containers
  community.docker.docker_compose_v2:
    project_src: "{{ bimdata_path }}"
    pull: "{{ install_offline | ternary('never', 'always') }}"
    remove_orphans: true
    state: present
