---
# External DB
- when: use_external_db | bool
  block:
  - name: "Check if all needed variables for database are defined if use_external_db: true."
    assert:
      that:
        - external_db_host is defined
        - external_db_host | length
        - external_db_port is defined
        - external_db_port | int
      fail_msg: "You choose to use an external database server (use_external_db: true), external_db_host, external_db_port must be defined and not empty."

  - name: "Set database connection variable when use_external_db: true."
    set_fact:
      db_api_host: "{{ external_db_host }}"
      db_connect_host: "{{ external_db_host }}"
      db_platform_host: "{{ external_db_host }}"
      db_iam_host: "{{ external_db_host }}"
      db_share_host: "{{ external_db_host }}"
      db_marketplace_host:  "{{ external_db_host }}"
      db_api_port: "{{ external_db_port }}"
      db_connect_port: "{{ external_db_port }}"
      db_platform_port: "{{ external_db_port }}"
      db_iam_port: "{{ external_db_port }}"
      db_share_port: "{{ external_db_port }}"
      db_marketplace_port: "{{ external_db_port }}"

# Not external DB
- when: not use_external_db | bool
  block:
  - name: "Check if app and db are the same host."
    set_fact:
      db_on_app: "{{ groups['db'] | default(None) == groups['app'] | default(false) }}"

  - name: "Set database connection variable accordingly."
    set_fact:
      db_api_host: "{{ db_on_app | ternary('api-db', db_server_addr) }}"
      db_connect_host: "{{ db_on_app | ternary('connect-db', db_server_addr) }}"
      db_platform_host: "{{ db_on_app | ternary('platform-db', db_server_addr) }}"
      db_iam_host: "{{ db_on_app | ternary('iam-db', db_server_addr) }}"
      db_share_host: "{{ db_on_app | ternary('share-db', db_server_addr) }}"
      db_marketplace_host: "{{ db_on_app | ternary('marketplace-db', db_server_addr) }}"

      db_api_port: "{{ db_on_app | ternary(5432, db_api_external_port) }}"
      db_connect_port: "{{ db_on_app | ternary(5432, db_connect_external_port) }}"
      db_platform_port: "{{ db_on_app | ternary(5432, db_platform_external_port) }}"
      db_iam_port: "{{ db_on_app | ternary(5432, db_iam_external_port) }}"
      db_share_port: "{{ db_on_app | ternary(5432, db_share_external_port) }}"
      db_marketplace_port: "{{ db_on_app | ternary(5432, db_marketplace_external_port) }}"

  - name: "Set docker-compose definition for databases."
    set_fact:
      compose_dbs: "{{ compose_dbs | default({}) | combine(lookup('template', 'compose_dbs.yml.j2') | from_yaml) }}"
    loop:
      - api
      - connect
      - platform
      - iam
      - share
