---
- name: "Check if all needed variables for s3 are defined."
  assert:
    that:
      - s3_endpoint_url is defined
      - s3_endpoint_url | length
      - s3_region_name is defined
      - s3_region_name | length
      - s3_access_key_id is defined
      - s3_access_key_id | length
      - s3_secret_access_key is defined
      - s3_secret_access_key | length
      - s3_storage_api_bucket_name is defined
      - s3_storage_api_bucket_name | length
      - s3_storage_connect_bucket_name is defined
      - s3_storage_connect_bucket_name | length
    fail_msg: >
      You choose to use an object storage (s3_enabled: true),
      s3_endpoint_url, s3_region_name, s3_access_key_id, s3_secret_access_key
      s3_storage_api_bucket_name, and s3_storage_connect_bucket_name must be defined and not empty.
