---
- name: "Check if all needed variables for swift are defined."
  assert:
    that:
      - swift_auth_url is defined
      - swift_auth_url | length
      - swift_username is defined
      - swift_username | length
      - swift_password is defined
      - swift_password | length
    fail_msg: >
      You choose to use an object storage (swift_enabled: true),
      swift_auth_url, swift_username and swift_password must be defined and not empty.
