---
- name: Check for incompatibilities in the TLS configuration
  ansible.builtin.fail:
    msg: "Only one of 'tls_enabled', 'tls_external' and 'tls_acme' can be set to true in the same time."
  when: _checklist | select() | list | length > 1
  vars:
    _checklist:
      - "{{ tls_enabled | bool }}"
      - "{{ tls_external | bool }}"
      - "{{ tls_acme | bool }}"

- name: Check if all needed variables for TLS are defined if needed
  ansible.builtin.assert:
    that:
      - tls_api_key | length
      - tls_api_cert | length

      - tls_connect_key | length
      - tls_connect_cert | length

      - tls_platform_back_key | length
      - tls_platform_back_cert | length

      - tls_platform_front_key | length
      - tls_platform_front_cert | length

      - tls_iam_key | length
      - tls_iam_cert | length

      - tls_documentation_key | length
      - tls_documentation_cert | length

      - tls_archive_key | length
      - tls_archive_cert | length
    fail_msg: >
      You choose to enable TLS (tls_enabled: true),
      you need to defined all the keys and certificates in group_vars/all/vars.yml.
  when: tls_enabled | bool

- name: Check if all needed variables for marketplace TLS are defined if needed
  ansible.builtin.assert:
    that:
      - tls_marketplace_back_key | length
      - tls_marketplace_back_cert | length

      - tls_marketplace_front_key | length
      - tls_marketplace_front_cert | length
    fail_msg: >
      You choose to enable TLS (tls_enabled: true),
      you need to defined all the keys and certificates in group_vars/all/tls.yml.
  when:
    - tls_enabled | bool
    - marketplace_enabled | bool

- name: Check if all needed variables for TLS are defined if needed
  ansible.builtin.assert:
    that:
      - tls_rabbitmq_admin_key | length
      - tls_rabbitmq_admin_cert | length
    fail_msg: >
      You choose to enable TLS (tls_enabled: true) and you don't use external rabbitmq,
      you need to defined the key and certificate in group_vars/all/tls.yml for rabbitmq.
  when:
    - tls_enabled | bool
    - not use_external_rabbitmq | bool

- name: Import TLS variables
  ansible.builtin.include_vars:
    file: tls.yml

- name: Import URLs variables
  ansible.builtin.include_vars:
    file: urls.yml
    name: urls
