---
- name: "Get installed docker-compose version."
  command: "{{ docker_compose_path }} --version"
  register: docker_compose_installed_version
  failed_when: false
  changed_when: false
  check_mode: false

- name: "Install docker-compose"
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: 0755
    force: yes
  environment: "{{ proxy_env }}"
  when: >
    docker_compose_installed_version.stdout is not defined
    or docker_compose_version not in docker_compose_current_version.stdout | default("")
