---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name: "{{ docker_apt_dependencies }}"
    state: present
    update_cache: true
  environment: "{{ proxy_env }}"

- name: "Remove legacy repository"
  ansible.builtin.file:
    path: "{{ docker_legacy_apt_repository_file }}"
    state: absent
  register: _remove_apt_legacy

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ docker_apt_repo_url }}"
    suites: "{{ docker_apt_repo_suites }}"
    components: "{{ docker_apt_repo_components }}"
    signed_by: "{{ docker_apt_repo_key_url }}"
    state: present
  environment: "{{ proxy_env }}"
  register: _add_apt_repo

- name: "Update apt cache if necessary"
  ansible.builtin.apt:
    update_cache: "{{ _remove_apt_legacy.changed or _add_apt_repo.changed }}"

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_pkg_name }}{% if docker_pkg_version != '' %}={{ docker_pkg_version }}{% endif %}"
    cache_valid_time: 3600
    state: present
    allow_change_held_packages: true
    allow_downgrade: true
  environment: "{{ proxy_env }}"
  notify: Restart Docker

- name: Hold Docker version
  ansible.builtin.dpkg_selections:
    name: "{{ docker_pkg_name }}"
    selection: "{{ docker_pkg_version_hold | ternary ('hold', 'install') }}"

- name: Install Docker compose
  ansible.builtin.apt:
    name: "{{ docker_compose_pkg_name }}{% if docker_compose_pkg_version != '' %}={{ docker_compose_pkg_version }}{% endif %}"
    cache_valid_time: 3600
    state: present
    allow_change_held_packages: true
    allow_downgrade: true
  environment: "{{ proxy_env }}"

- name: Hold Docker compose version
  ansible.builtin.dpkg_selections:
    name: "{{ docker_compose_pkg_name }}"
    selection: "{{ docker_compose_pkg_version_hold | ternary ('hold', 'install') }}"
