---
- name: "Cleanup legacy key in main keyring if needed."
  ansible.builtin.apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: absent

- name: "Cleanup legacy Docker repository."
  ansible.builtin.apt_repository:
    filename: docker
    repo: >
      deb [arch=amd64] {{ docker_repo_url }}/{{ ansible_distribution | lower }}
      {{ ansible_distribution_release }} {{ docker_apt_release_channel }}
    update_cache: false
    state: absent

- name: Install Docker prerequisites
  ansible.builtin.apt:
    name: "{{ docker_apt_dependencies }}"
    state: present
    update_cache: true
  environment: "{{ proxy_env }}"

- name: Make sur docker keyring folder exists
  ansible.builtin.file:
    path: "{{ docker_apt_keyring_path | dirname }}"
    state: directory
    mode: '0755'

- name: Add Docker key
  ansible.builtin.get_url:
    url: "{{ docker_apt_repo_key_url }}"
    dest: "{{ docker_apt_keyring_path }}"
    mode: '0644'
    force: true
  environment: "{{ proxy_env }}"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "{{ docker_apt_repo }}"
    update_cache: true
    state: present
  environment: "{{ proxy_env }}"

- name: Hold Docker version
  ansible.builtin.dpkg_selections:
    name: "{{ docker_pkg_name }}"
    selection: "{{ docker_pkg_version_hold | ternary ('hold', 'install') }}"

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ docker_pkg_name }}{% if docker_pkg_version != '' %}={{ docker_pkg_version }}{% endif %}"
    cache_valid_time: 3600
    state: present
    allow_change_held_packages: true
  environment: "{{ proxy_env }}"
  notify: Restart Docker

- name: Hold Docker compose version
  ansible.builtin.dpkg_selections:
    name: "{{ docker_compose_pkg_name }}"
    selection: "{{ docker_compose_pkg_version_hold | ternary ('hold', 'install') }}"

- name: Install Docker compose
  ansible.builtin.apt:
    name: "{{ docker_compose_pkg_name }}{% if docker_compose_pkg_version != '' %}={{ docker_pkg_version }}{% endif %}"
    cache_valid_time: 3600
    state: present
    allow_change_held_packages: true
  environment: "{{ proxy_env }}"
