---
- name: Add Docker key
  ansible.builtin.rpm_key:
    key: "{{ docker_dnf_repo_key_url }}"
    state: present
  environment: "{{ proxy_env }}"

- name: Add Docker repository
  ansible.builtin.get_url:
    url: "{{ docker_dnf_repo }}"
    dest: "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
    owner: root
    group: root
    mode: "0644"
  environment: "{{ proxy_env }}"

- name: Install Docker (DNF)
  ansible.builtin.dnf:
    name: "{{ docker_pkg_name }}"
    update_cache: true
    state: present
  environment: "{{ proxy_env }}"
  notify: Restart Docker

- name: Install Docker compose (DNF)
  ansible.builtin.dnf:
    name: "{{ docker_compose_pkg_name }}"
    update_cache: true
    state: present
  environment: "{{ proxy_env }}"
