---
- name: "Include tasks for CentOS if needed."
  include_tasks: install-redhat.yml
  when: ansible_os_family | lower == "redhat"

- name: "Include tasks for Debian if needed."
  include_tasks: install-debian.yml
  when: ansible_os_family | lower == "debian"

- name: "Create docker service systemd directory."
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0640
  when: >
    (http_proxy is defined and http_proxy | length)
    or (https_proxy is defined and https_proxy | length)
    
- name: "Configure docker proxy if needed."
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0640
  when: >
    (http_proxy is defined and http_proxy | length)
    or (https_proxy is defined and https_proxy | length)
  notify: "Restart Docker."

- name: "Flush handlers to avoid any conflict with the desired state."
  meta: flush_handlers

- name: "Configure Docker service startup."
  service:
    name: "{{ docker_svc_name }}"
    state: "{{ docker_svc_state }}"
    enabled: "{{ docker_svc_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"
