---
- name: "Login to the define docker registries."
  docker_login:
    registry: "{{ item.url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
  loop: "{{ docker_registries }}"
  no_log: true
