---
- name: "Retrieve previous version"
  ansible.builtin.set_fact:
    _previous_version: "{{
        post_upgrade_version
        | default(
          hostvars[groups['app'][0]]['_previous_compose_content']['services']['api']['image'].split(':')[-1]
          if hostvars[groups['app'][0]]['_previous_compose_content'] is defined
          else 0
        )
      }}"

- name: "Apply needed post_upgrade tasks if this is a different version"
  when:
    - (_previous_version | int) != (bimdata_version | int )
  block:
    - name: "Print which version are use to determine which post upgrade tasks to run"
      ansible.builtin.debug:
        msg: "Post-upgrade from {{ _previous_version }} to {{ bimdata_version }}."

    - name: "Include tasks for 20241016 upgrade."
      ansible.builtin.include_tasks: "20241016.yml"
      when:
        - not _first_deploy | bool
        - _previous_version | int < 20241016
    - name: "Include tasks for 20250107 upgrade."
      ansible.builtin.include_tasks: "20250107.yml"
      when:
        - not _first_deploy | bool
        - _previous_version | int < 20250107
# End of block
