---
# Version
bimdata_version: 20240528

# DNS subdomains
api_dns_name: "api.{{ app_dns_domain }}"
connect_dns_name: "connect.{{ app_dns_domain }}"
platform_back_dns_name: "platform-back.{{ app_dns_domain }}"
platform_front_dns_name: "platform.{{ app_dns_domain }}"
iam_dns_name: "iam.{{ app_dns_domain }}"
rabbitmq_admin_dns_name: "rabbitmq.{{ app_dns_domain }}"
documentation_dns_name: "doc.{{ app_dns_domain }}"
archive_dns_name: "archive.{{ app_dns_domain }}"
marketplace_back_dns_name: "marketplace-back.{{ app_dns_domain }}"
marketplace_front_dns_name: "marketplace.{{ app_dns_domain }}"

# smtp service
smtp_host: ""
smtp_port: 587
smtp_user: ""
smtp_pass: "{{ vault_smtp_pass }}"
smtp_use_tls: true
smtp_default_email: ""
debug_mail_to: ""

# Web frontal
external_port_http: 80
external_port_https: 443
max_upload_size: 1g

# Some path where data will be stored
bimdata_path: /opt/bimdata
bimdata_docker_volume_path: "{{ bimdata_path }}/data"
bimdata_venv_path: "{{ bimdata_path }}/venv"

# Object storage
s3_enabled: false
s3_connect_enabled: "{{ s3_enabled }}"
s3_endpoint_url: ""
s3_region_name: ""
s3_access_key_id: ""
s3_secret_access_key: "{{ vault_s3_secret_access_key }}"
s3_multipart_threshold: "{{ '5 GB' | human_to_bytes }}"
# List of dicts [{'name': option_name, 'value': option_value}]
s3_other_options: []

# Api and Connect need a different bucket
s3_storage_api_bucket_name: ""
s3_storage_connect_bucket_name: ""

# When Object Storage is enable, connect needs to know the URL
# for the Content Security Policy to be able to load profile pictures
csp_storage_url: "https://{{ s3_storage_connect_bucket_name }}.{{ (s3_endpoint_url | urlsplit).hostname }}"

# api
api_secret_key: "{{ vault_api_secret_key }}" # Change me in the vault

# connect
connect_secret_key: "{{ vault_connect_secret_key }}" # Change me in the vault
connect_client_id: "{{ 'connect_client_id' | to_uuid(namespace=uuid_namespace) }}"
connect_client_secret: "{{ 'connect_client_secret' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_secret: "{{ vault_connect_invitation_secret }}" # Change me in the vault
connect_invitation_client: "{{ 'connect_invitation_client' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_client_secret: "{{ vault_connect_invitation_client_secret }}" # Change me in the vault
connect_use_custom_mail_templates: false

# platform back
platform_back_secret_key: "{{ vault_platform_back_secret_key }}" # Change me in the vault
platform_back_client_id: "{{ 'platform_back_client_id' | to_uuid(namespace=uuid_namespace) }}"
platform_back_client_secret: "{{ vault_platform_back_client_secret }}"
platform_back_webhook_secret: "{{ vault_platform_back_webhook_secret }}" # Change me in the vault
platform_back_use_custom_mail_templates: false
platform_back_enable_cron: true

# platform
platform_front_client_id: "{{ 'platform_front_client_id' | to_uuid(namespace=uuid_namespace) }}"
platform_front_project_status_limit_new: "5"
platform_front_project_status_limit_active: "15"
platform_front_authorized_identity_providers: "bimdataconnect"
platform_front_translate_ifc_type: false

# Archive
archive_prefix: "bimdata-"

# iam
iam_user: "admin"
iam_password: "{{ vault_iam_password }}" # Change me in the vault

# Archive
archive_workers_nb: 2

# Marketplace
marketplace_enabled: false
# Marketplace_back
marketplace_back_secret_key: "{{ vault_marketplace_back_secret_key }}" # Change me in the vault
marketplace_back_use_custom_mail_templates: false

# Marketplace_front
marketplace_front_workers: 2
marketplace_front_client_id: "{{ 'marketplace_front_client_id' | to_uuid(namespace=uuid_namespace) }}"

# SSO invitations
sso_invitation_enabled: false
sso_invitation_secret: "{{ sso_invitation_enabled | ternary(vault_sso_invitation_secret, '') }}"

# workers
## export
workers_export_instance: 1
workers_export_cpu: 1
workers_export_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_export_task_timeout: "{{ '2h' | community.general.to_seconds | int }}"

## gltf
workers_gltf_instance: 1
workers_gltf_cpu: 1
workers_gltf_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_gltf_task_timeout: "{{ '10h' | community.general.to_seconds | int }}"

## extract
workers_extract_instance: 1
workers_extract_cpu: 1
workers_extract_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_extract_task_timeout: "{{ '2h' | community.general.to_seconds | int }}"

## svg
workers_svg_instance: 1
workers_svg_cpu: 1
workers_svg_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_svg_task_timeout: "{{ '2h' | community.general.to_seconds | int }}"

## merge
workers_merge_instance: 1
workers_merge_cpu: 1
workers_merge_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_merge_task_timeout: "{{ '2h' | community.general.to_seconds | int }}"

## xkt
workers_xkt_instance: 1
workers_xkt_cpu: 1
workers_xkt_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_xkt_task_timeout: "{{ '3min' | community.general.to_seconds | int }}"

workers_xkt_v10_instance: 1
workers_xkt_v10_cpu: 1
workers_xkt_v10_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_xkt_v10_task_timeout: "{{ '3min' | community.general.to_seconds | int }}"

## preview 3D
workers_preview_instance: 1
workers_preview_cpu: 1
workers_preview_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_preview_task_timeout: "{{ '3min' | community.general.to_seconds | int }}"

## preview 2D
workers_preview_2d_instance: 1
workers_preview_2d_cpu: 1
workers_preview_2d_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_preview_2d_task_timeout: "{{ '10min' | community.general.to_seconds | int }}"

## preview PDF
workers_preview_pdf_instance: 1
workers_preview_pdf_cpu: 1
workers_preview_pdf_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_preview_pdf_task_timeout: "{{ '10min' | community.general.to_seconds | int }}"

## dwg
workers_dwg_properties_instance: 1
workers_dwg_properties_cpu: 1
workers_dwg_properties_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_dwg_properties_task_timeout: "{{ '1h' | community.general.to_seconds | int }}"

workers_dwg_geometries_instance: 1
workers_dwg_geometries_cpu: 1
workers_dwg_geometries_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_dwg_geometries_task_timeout: "{{ '4h' | community.general.to_seconds | int }}"

## Pointcloud
workers_pointcloud_instance: 1
workers_pointcloud_cpu: 1
workers_pointcloud_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_pointcloud_task_timeout: "{{ '10h' | community.general.to_seconds | int }}"

## b2d
workers_b2d_instance: 1
workers_b2d_cpu: 1
workers_b2d_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_b2d_task_timeout: "{{ '30m' | community.general.to_seconds | int }}"

# Map
# By default it uses our default token, uncomment and specify your token if needed
# https://docs.maptiler.com/cloud/api/authentication-key/
# maptiler_token: ""

# Misc
uuid_namespace: "{{ app_dns_domain | to_uuid }}"
master_token: "{{ vault_master_token }}"
app_env: on-premises
