---
# Offline installation: no dependancy will be pull from Internet
install_offline: false
install_offline_cache_path: "{{ bimdata_path }}/offline-cache"
install_offline_clear_cache: false

install_offline_docker:
  - name: "docker-app-images-{{ docker_bimdata_tag }}.tar.bz2"
    group: app

  - name: "docker-bdd-images-{{ docker_bimdata_tag }}.tar.bz2"
    group: db

  - name: "docker-worker-images-{{ docker_bimdata_tag }}.tar.bz2"
    group: workers
