---
# DNS Domain
app_dns_domain: domain.tld

# DNS subdomains
api_dns_name: "api.{{ app_dns_domain }}"
connect_dns_name: "connect.{{ app_dns_domain }}"
platform_back_dns_name: "platform-back.{{ app_dns_domain }}"
platform_front_dns_name: "platform.{{ app_dns_domain }}"
iam_dns_name: "iam.{{ app_dns_domain }}"
documentation_dns_name: "doc.{{ app_dns_domain }}"
share_dns_name: "share.{{ app_dns_domain }}"
archive_dns_name: "archive.{{ app_dns_domain }}"
marketplace_back_dns_name: "marketplace-back.{{ app_dns_domain }}"
marketplace_front_dns_name: "marketplace.{{ app_dns_domain }}"

# smtp service
smtp_host: ""
smtp_port: 587
smtp_user: ""
smtp_pass: "{{ vault_smtp_pass }}"
smtp_use_tls: true
smtp_default_email: ""

# Web frontal
external_port_http: 80
external_port_https: 443
max_upload_size: 1g

# Some path where data will be stored
bimdata_path: /opt/bimdata
bimdata_docker_volume_path: "{{ bimdata_path }}/datas"
bimdata_dockerfiles_path: "{{ bimdata_path }}/dockerfiles"

# Obect storage
swift_enabled: false
swift_auth_url: ""
swift_tenant_id: ""
swift_tenant_name: ""
swift_username: ""
swift_password: "{{ vault_swift_password }}"
swift_temp_url_key: ""
swift_container_name: ""

# api
api_secret_key: "{{ vault_api_secret_key }}"  # Change me in the vault

# connect
connect_secret_key: "{{ vault_connect_secret_key }}"  # Change me in the vault
connect_client_id: "{{ 'connect_client_id' | to_uuid(namespace=uuid_namespace) }}"
connect_client_secret: "{{ 'connect_client_secret' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_secret: "{{ vault_connect_invitation_secret }}"  # Change me in the vault
connect_invitation_client: "{{ 'connect_invitation_client' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_client_secret: "{{ vault_connect_invitation_client_secret }}"  # Change me in the vault

# platform back
platform_back_secret_key: "{{ vault_platform_back_secret_key }}"  # Change me in the vault
platform_back_webhook_secret: "{{ vault_platform_back_webhook_secret }}"  # Change me in the vault

# platform
platform_front_client_id: "{{ 'platform_front_client_id' | to_uuid(namespace=uuid_namespace) }}"

# iam
iam_user: "admin"
iam_password: "{{ vault_iam_password }}"  # Change me in the vault

# Documentation
playground_client_id: none

# Share
share_secret_key: "{{ vault_share_secret_key }}"

# Archive
archive_workers_nb: 2

# Marketplace_back
marketplace_back_secret_key: "{{ vault_marketplace_back_secret_key }}"  # Change me in the vault
marketplace_header_secure_string: "{{ vault_marketplace_header_secure_string }}"  # Change me in the vault
# Marketplace_front
Marketplace_front_workers: 2

# workers
## export
workers_export_instance: 1
workers_export_cpu: 1

## gltf
workers_gltf_instance: 1
workers_gltf_cpu: 1

## extract
workers_extract_instance: 1
workers_extract_cpu: 1

## extract with quantities
workers_extract_quantities_instance: 1
workers_extract_quantities_cpu: 1

## svg
workers_svg_instance: 1
workers_svg_cpu: 1

## bvh tree
workers_bvh_instance: 1
workers_bvh_cpu: 1

## optimize
workers_optimize_instance: 1
workers_optimize_cpu: 1

## merge
workers_merge_instance: 1
workers_merge_cpu: 1

## xkt
workers_xkt_instance: 1
workers_xkt_cpu: 1

## preview
workers_preview_instance: 1
workers_preview_cpu: 1

# Misc
uuid_namespace: "{{ app_dns_domain | to_uuid }}"
master_token: "{{ vault_master_token }}"
app_env: staging
mapbox_token: "{{ vault_mapbox_token }}"
