---
# DNS Domain
app_dns_domain: test.domain.tld

# DNS subdomains
api_dns_name: "api.{{ app_dns_domain }}"
connect_dns_name: "connect.{{ app_dns_domain }}"
platform_back_dns_name: "platform-back.{{ app_dns_domain }}"
platform_front_dns_name: "platform.{{ app_dns_domain }}"
iam_dns_name: "iam.{{ app_dns_domain }}"
documentation_dns_name: "doc.{{ app_dns_domain }}"
archive_dns_name: "archive.{{ app_dns_domain }}"
marketplace_back_dns_name: "marketplace-back.{{ app_dns_domain }}"
marketplace_front_dns_name: "marketplace.{{ app_dns_domain }}"

# smtp service
smtp_host: ""
smtp_port: 587
smtp_user: ""
smtp_pass: "{{ vault_smtp_pass }}"
smtp_use_tls: true
smtp_default_email: ""
debug_mail_to: ""

# Web frontal
external_port_http: 80
external_port_https: 443
max_upload_size: 1g

# Some path where data will be stored
bimdata_path: /opt/bimdata
bimdata_docker_volume_path: "{{ bimdata_path }}/data"
bimdata_venv_path: "{{ bimdata_path }}/venv"

# Obect storage
swift_enabled: false
swift_auth_url: ""
swift_tenant_id: ""
swift_tenant_name: ""
swift_region_name: ""
swift_username: ""
swift_password: "{{ vault_swift_password }}"
swift_temp_url_key: "{{ vault_swift_temp_url_key }}"
# Api and Connect need a different container
swift_api_container_name: ""
swift_connect_container_name: ""

# api
api_secret_key: "{{ vault_api_secret_key }}" # Change me in the vault

# connect
connect_secret_key: "{{ vault_connect_secret_key }}" # Change me in the vault
connect_client_id: "{{ 'connect_client_id' | to_uuid(namespace=uuid_namespace) }}"
connect_client_secret: "{{ 'connect_client_secret' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_secret: "{{ vault_connect_invitation_secret }}" # Change me in the vault
connect_invitation_client: "{{ 'connect_invitation_client' | to_uuid(namespace=uuid_namespace) }}"
connect_invitation_client_secret: "{{ vault_connect_invitation_client_secret }}" # Change me in the vault

# platform back
platform_back_secret_key: "{{ vault_platform_back_secret_key }}" # Change me in the vault
platform_back_webhook_secret: "{{ vault_platform_back_webhook_secret }}" # Change me in the vault

# platform
platform_front_client_id: "{{ 'platform_front_client_id' | to_uuid(namespace=uuid_namespace) }}"
platform_front_project_status_limit_new: "5"
platform_front_project_status_limit_active: "15"

# iam
iam_user: "admin"
iam_password: "{{ vault_iam_password }}" # Change me in the vault

# Archive
archive_workers_nb: 2

# Marketplace
marketplace_enabled: false
# Marketplace_back
marketplace_back_secret_key: "{{ vault_marketplace_back_secret_key }}" # Change me in the vault

# Marketplace_front
marketplace_front_workers: 2
marketplace_front_client_id: "{{ 'marketplace_front_client_id' | to_uuid(namespace=uuid_namespace) }}"

# workers
## export
workers_export_instance: 1
workers_export_cpu: 1
workers_export_ram: "{{ ansible_memtotal_mb / 2 }}m"

## gltf
workers_gltf_instance: 1
workers_gltf_cpu: 1
workers_gltf_ram: "{{ ansible_memtotal_mb / 2 }}m"

## extract
workers_extract_instance: 1
workers_extract_cpu: 1
workers_extract_ram: "{{ ansible_memtotal_mb / 2 }}m"

## svg
workers_svg_instance: 1
workers_svg_cpu: 1
workers_svg_ram: "{{ ansible_memtotal_mb / 2 }}m"

## merge
workers_merge_instance: 1
workers_merge_cpu: 1
workers_merge_ram: "{{ ansible_memtotal_mb / 2 }}m"

## xkt
workers_xkt_instance: 1
workers_xkt_cpu: 1
workers_xkt_ram: "{{ ansible_memtotal_mb / 2 }}m"
workers_xkt_task_timeout: 180

## preview
workers_preview_instance: 1
workers_preview_cpu: 1
workers_preview_ram: "{{ ansible_memtotal_mb / 2 }}m"

## dwg
workers_dwg_properties_instance: 1
workers_dwg_properties_cpu: 1
workers_dwg_properties_ram: "{{ ansible_memtotal_mb / 2 }}m"

workers_dwg_geometries_instance: 1
workers_dwg_geometries_cpu: 1
workers_dwg_geometries_ram: "{{ ansible_memtotal_mb / 2 }}m"

# Map
# By default it uses our default token, uncomment and specify your token if needed
# https://docs.maptiler.com/cloud/api/authentication-key/
# maptiler_token: ""

# Misc
uuid_namespace: "{{ app_dns_domain | to_uuid }}"
master_token: "{{ vault_master_token }}"
app_env: on-premises
