---
# A lot of the nginx configuration is handle automaticly by the docker image
# we are using: https://hub.docker.com/r/jwilder/nginx-proxy
# We only add some stuff to specific vhost

nginx_custom_conf: |
  client_max_body_size {{ max_upload_size }};

  gzip on;
  gzip_proxied any;
  gzip_vary on;
  gzip_comp_level 6;

  proxy_connect_timeout       20m;
  proxy_send_timeout          20m;
  proxy_read_timeout          20m;
  send_timeout                20m;

  gzip_types application/octet-stream;

  proxy_buffer_size          128k;
  proxy_buffers              4 256k;
  proxy_busy_buffers_size    256k;

nginx_vhost_override:
  - vhost: "{{ api_dns_name }}"
    config: |
      {% if not swift_enabled | bool %}
      location /storage/ {
        alias /var/www/static/api_storage/;
        add_header 'Access-Control-Allow-Origin' '*';
        # Preflighted requests
        if ($request_method = OPTIONS ) {
          add_header 'Access-Control-Allow-Origin'  '*';
          add_header 'Access-Control-Allow-Methods' 'OPTIONS, HEAD, GET';
          add_header 'Access-Control-Allow-Headers' 'Authorization, Origin, X-Requested-With, Content-Type, Accept';
          return 204;
        }
      }
      {% endif %}
  - vhost: "{{ connect_dns_name }}"
    config: |
      {% if not swift_enabled | bool %}
      location /storage/ {
        alias /var/www/static/connect_storage/;
        add_header 'Access-Control-Allow-Origin' '*';
        # Preflighted requests
        if ($request_method = OPTIONS ) {
          add_header 'Access-Control-Allow-Origin'  '*';
          add_header 'Access-Control-Allow-Methods' 'OPTIONS, HEAD, GET';
          add_header 'Access-Control-Allow-Headers' 'Authorization, Origin, X-Requested-With, Content-Type, Accept';
          return 204;
        }
      }
      {% endif %}
