---
vault_docker_private_registry_password: CHANGEME-BY-YOUR-PASSWORD-ON-THE-REGISTRY

vault_master_token: CHANGEME-BY-SOMETHING-SECURE
# Create a mapbox token: https://docs.mapbox.com/help/tutorials/get-started-tokens-api/#creating-temporary-tokens
vault_mapbox_token: CHANGEME-BY-YOUR-MAPBOX-TOKEN

vault_db_api_password: CHANGEME-BY-SOMETHING-SECURE
vault_db_connect_password: CHANGEME-BY-SOMETHING-SECURE
vault_db_platform_password: CHANGEME-BY-SOMETHING-SECURE
vault_db_iam_password: CHANGEME-BY-SOMETHING-SECURE

vault_rabbitmq_password: CHANGEME-BY-SOMETHING-SECURE
vault_api_secret_key: CHANGEME-BY-SOMETHING-SECURE
vault_connect_secret_key: CHANGEME-BY-SOMETHING-SECURE
vault_connect_invitation_secret: CHANGEME-BY-SOMETHING-SECURE
vault_connect_invitation_client_secret: CHANGEME-BY-SOMETHING-SECURE
vault_platform_back_secret_key: CHANGEME-BY-SOMETHING-SECURE
vault_platform_back_webhook_secret: CHANGEME-BY-SOMETHING-SECURE
vault_iam_password: CHANGEME-BY-SOMETHING-SECURE
vault_iam_truststore_password: CHANGEME-BY-SOMETHING-SECURE

vault_smtp_pass: CHANGEME-BY-YOUR-PASSWORD-ON-THE-SMTP-SERVER

vault_tls_api_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----

vault_tls_connect_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----

vault_tls_platform_back_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----

vault_tls_platform_front_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----

vault_tls_iam_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----

vault_tls_rabbitmq_admin_key: |
  -----BEGIN EC PRIVATE KEY-----
  CHANGEME CHANGEME CHANGEME
  CHANGEME CHANGEME CHANGEME
  -----END EC PRIVATE KEY-----
