name: Buld and push images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [self-hosted, common]
    if: endsWith(github.ref_name, '.0')
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v2
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run the script to tag the images
        run: ./.github/scripts/tag_images.sh
